source 'https://rubygems.org'

ruby '>= 2.7.0'

gem 'cucumber', '~> 8.0'
gem 'rspec', '~> 3.12'
gem 'rspec-expectations', '~> 3.12'
gem 'httparty', '~> 0.21'
gem 'json', '~> 2.6'
gem 'json-schema', '~> 4.0'







